/**
 * CompletionMessageTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionMessageTool extends CompletionMessage {
    private String toolCallId;

    @JsonSetter("tool_call_id")
    public void setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
    }

    @JsonGetter("tool_call_id")
    public String getToolCallId() {
        return this.toolCallId;
    }
}

