/**
 * CompletionTokensDetails automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionTokensDetails {
    private Integer acceptedPredictionTokens;
    private Integer audioTokens;
    private Integer reasoningTokens;
    private Integer rejectedPredictionTokens;

    @JsonSetter("accepted_prediction_tokens")
    public void setAcceptedPredictionTokens(Integer acceptedPredictionTokens) {
        this.acceptedPredictionTokens = acceptedPredictionTokens;
    }

    @JsonGetter("accepted_prediction_tokens")
    public Integer getAcceptedPredictionTokens() {
        return this.acceptedPredictionTokens;
    }

    @JsonSetter("audio_tokens")
    public void setAudioTokens(Integer audioTokens) {
        this.audioTokens = audioTokens;
    }

    @JsonGetter("audio_tokens")
    public Integer getAudioTokens() {
        return this.audioTokens;
    }

    @JsonSetter("reasoning_tokens")
    public void setReasoningTokens(Integer reasoningTokens) {
        this.reasoningTokens = reasoningTokens;
    }

    @JsonGetter("reasoning_tokens")
    public Integer getReasoningTokens() {
        return this.reasoningTokens;
    }

    @JsonSetter("rejected_prediction_tokens")
    public void setRejectedPredictionTokens(Integer rejectedPredictionTokens) {
        this.rejectedPredictionTokens = rejectedPredictionTokens;
    }

    @JsonGetter("rejected_prediction_tokens")
    public Integer getRejectedPredictionTokens() {
        return this.rejectedPredictionTokens;
    }
}

