/**
 * CompletionRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionRequest {
    private String model;
    private java.util.List<CompletionMessage> messages;
    private Double frequencyPenalty;
    private java.util.Map<String, Integer> logitBias;
    private Boolean logprobs;
    private Integer maxCompletionTokens;
    private java.util.Map<String, String> metadata;
    private Double presencePenalty;
    private String reasoningEffort;
    private Integer seed;
    private String serviceTier;
    private java.util.List<String> stop;
    private Boolean store;
    private Double temperature;
    private Integer topLogprobs;
    private Double topP;
    private String user;

    @JsonSetter("model")
    public void setModel(String model) {
        this.model = model;
    }

    @JsonGetter("model")
    public String getModel() {
        return this.model;
    }

    @JsonSetter("messages")
    public void setMessages(java.util.List<CompletionMessage> messages) {
        this.messages = messages;
    }

    @JsonGetter("messages")
    public java.util.List<CompletionMessage> getMessages() {
        return this.messages;
    }

    @JsonSetter("frequency_penalty")
    public void setFrequencyPenalty(Double frequencyPenalty) {
        this.frequencyPenalty = frequencyPenalty;
    }

    @JsonGetter("frequency_penalty")
    public Double getFrequencyPenalty() {
        return this.frequencyPenalty;
    }

    @JsonSetter("logit_bias")
    public void setLogitBias(java.util.Map<String, Integer> logitBias) {
        this.logitBias = logitBias;
    }

    @JsonGetter("logit_bias")
    public java.util.Map<String, Integer> getLogitBias() {
        return this.logitBias;
    }

    @JsonSetter("logprobs")
    public void setLogprobs(Boolean logprobs) {
        this.logprobs = logprobs;
    }

    @JsonGetter("logprobs")
    public Boolean getLogprobs() {
        return this.logprobs;
    }

    @JsonSetter("max_completion_tokens")
    public void setMaxCompletionTokens(Integer maxCompletionTokens) {
        this.maxCompletionTokens = maxCompletionTokens;
    }

    @JsonGetter("max_completion_tokens")
    public Integer getMaxCompletionTokens() {
        return this.maxCompletionTokens;
    }

    @JsonSetter("metadata")
    public void setMetadata(java.util.Map<String, String> metadata) {
        this.metadata = metadata;
    }

    @JsonGetter("metadata")
    public java.util.Map<String, String> getMetadata() {
        return this.metadata;
    }

    @JsonSetter("presence_penalty")
    public void setPresencePenalty(Double presencePenalty) {
        this.presencePenalty = presencePenalty;
    }

    @JsonGetter("presence_penalty")
    public Double getPresencePenalty() {
        return this.presencePenalty;
    }

    @JsonSetter("reasoning_effort")
    public void setReasoningEffort(String reasoningEffort) {
        this.reasoningEffort = reasoningEffort;
    }

    @JsonGetter("reasoning_effort")
    public String getReasoningEffort() {
        return this.reasoningEffort;
    }

    @JsonSetter("seed")
    public void setSeed(Integer seed) {
        this.seed = seed;
    }

    @JsonGetter("seed")
    public Integer getSeed() {
        return this.seed;
    }

    @JsonSetter("service_tier")
    public void setServiceTier(String serviceTier) {
        this.serviceTier = serviceTier;
    }

    @JsonGetter("service_tier")
    public String getServiceTier() {
        return this.serviceTier;
    }

    @JsonSetter("stop")
    public void setStop(java.util.List<String> stop) {
        this.stop = stop;
    }

    @JsonGetter("stop")
    public java.util.List<String> getStop() {
        return this.stop;
    }

    @JsonSetter("store")
    public void setStore(Boolean store) {
        this.store = store;
    }

    @JsonGetter("store")
    public Boolean getStore() {
        return this.store;
    }

    @JsonSetter("temperature")
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    @JsonGetter("temperature")
    public Double getTemperature() {
        return this.temperature;
    }

    @JsonSetter("top_logprobs")
    public void setTopLogprobs(Integer topLogprobs) {
        this.topLogprobs = topLogprobs;
    }

    @JsonGetter("top_logprobs")
    public Integer getTopLogprobs() {
        return this.topLogprobs;
    }

    @JsonSetter("top_p")
    public void setTopP(Double topP) {
        this.topP = topP;
    }

    @JsonGetter("top_p")
    public Double getTopP() {
        return this.topP;
    }

    @JsonSetter("user")
    public void setUser(String user) {
        this.user = user;
    }

    @JsonGetter("user")
    public String getUser() {
        return this.user;
    }
}

