/**
 * CompletionUsage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionUsage {
    private Integer completionTokens;
    private Integer promptTokens;
    private Integer totalTokens;
    private CompletionTokensDetails completionTokensDetails;
    private PromptTokensDetails promptTokensDetails;

    @JsonSetter("completion_tokens")
    public void setCompletionTokens(Integer completionTokens) {
        this.completionTokens = completionTokens;
    }

    @JsonGetter("completion_tokens")
    public Integer getCompletionTokens() {
        return this.completionTokens;
    }

    @JsonSetter("prompt_tokens")
    public void setPromptTokens(Integer promptTokens) {
        this.promptTokens = promptTokens;
    }

    @JsonGetter("prompt_tokens")
    public Integer getPromptTokens() {
        return this.promptTokens;
    }

    @JsonSetter("total_tokens")
    public void setTotalTokens(Integer totalTokens) {
        this.totalTokens = totalTokens;
    }

    @JsonGetter("total_tokens")
    public Integer getTotalTokens() {
        return this.totalTokens;
    }

    @JsonSetter("completion_tokens_details")
    public void setCompletionTokensDetails(CompletionTokensDetails completionTokensDetails) {
        this.completionTokensDetails = completionTokensDetails;
    }

    @JsonGetter("completion_tokens_details")
    public CompletionTokensDetails getCompletionTokensDetails() {
        return this.completionTokensDetails;
    }

    @JsonSetter("prompt_tokens_details")
    public void setPromptTokensDetails(PromptTokensDetails promptTokensDetails) {
        this.promptTokensDetails = promptTokensDetails;
    }

    @JsonGetter("prompt_tokens_details")
    public PromptTokensDetails getPromptTokensDetails() {
        return this.promptTokensDetails;
    }
}

