/**
 * CompletionMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "role")
@JsonSubTypes({
    @JsonSubTypes.Type(value = CompletionMessageDeveloper.class, name = "developer"),
    @JsonSubTypes.Type(value = CompletionMessageSystem.class, name = "system"),
    @JsonSubTypes.Type(value = CompletionMessageUser.class, name = "user"),
    @JsonSubTypes.Type(value = CompletionMessageAssistant.class, name = "assistant"),
    @JsonSubTypes.Type(value = CompletionMessageTool.class, name = "tool"),
})
public abstract class CompletionMessage {
    private String role;
    private String content;

    @JsonSetter("role")
    public void setRole(String role) {
        this.role = role;
    }

    @JsonGetter("role")
    public String getRole() {
        return this.role;
    }

    @JsonSetter("content")
    public void setContent(String content) {
        this.content = content;
    }

    @JsonGetter("content")
    public String getContent() {
        return this.content;
    }
}

