/**
 * CompletionChoice automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionChoice {
    private Integer index;
    private CompletionMessage message;
    private String finishReason;

    @JsonSetter("index")
    public void setIndex(Integer index) {
        this.index = index;
    }

    @JsonGetter("index")
    public Integer getIndex() {
        return this.index;
    }

    @JsonSetter("message")
    public void setMessage(CompletionMessage message) {
        this.message = message;
    }

    @JsonGetter("message")
    public CompletionMessage getMessage() {
        return this.message;
    }

    @JsonSetter("finish_reason")
    public void setFinishReason(String finishReason) {
        this.finishReason = finishReason;
    }

    @JsonGetter("finish_reason")
    public String getFinishReason() {
        return this.finishReason;
    }
}

