/**
 * CompletionResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionResponse {
    private String id;
    private String object;
    private Integer created;
    private String model;
    private java.util.List<CompletionChoice> choices;
    private CompletionUsage usage;
    private String serviceTier;
    private String systemFingerprint;

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("object")
    public void setObject(String object) {
        this.object = object;
    }

    @JsonGetter("object")
    public String getObject() {
        return this.object;
    }

    @JsonSetter("created")
    public void setCreated(Integer created) {
        this.created = created;
    }

    @JsonGetter("created")
    public Integer getCreated() {
        return this.created;
    }

    @JsonSetter("model")
    public void setModel(String model) {
        this.model = model;
    }

    @JsonGetter("model")
    public String getModel() {
        return this.model;
    }

    @JsonSetter("choices")
    public void setChoices(java.util.List<CompletionChoice> choices) {
        this.choices = choices;
    }

    @JsonGetter("choices")
    public java.util.List<CompletionChoice> getChoices() {
        return this.choices;
    }

    @JsonSetter("usage")
    public void setUsage(CompletionUsage usage) {
        this.usage = usage;
    }

    @JsonGetter("usage")
    public CompletionUsage getUsage() {
        return this.usage;
    }

    @JsonSetter("service_tier")
    public void setServiceTier(String serviceTier) {
        this.serviceTier = serviceTier;
    }

    @JsonGetter("service_tier")
    public String getServiceTier() {
        return this.serviceTier;
    }

    @JsonSetter("system_fingerprint")
    public void setSystemFingerprint(String systemFingerprint) {
        this.systemFingerprint = systemFingerprint;
    }

    @JsonGetter("system_fingerprint")
    public String getSystemFingerprint() {
        return this.systemFingerprint;
    }
}

