/**
 * CompletionMessageAssistant automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class CompletionMessageAssistant extends CompletionMessage {
    private String audio;
    private String name;
    private String refusal;
    private java.util.List<String> toolCalls;

    @JsonSetter("audio")
    public void setAudio(String audio) {
        this.audio = audio;
    }

    @JsonGetter("audio")
    public String getAudio() {
        return this.audio;
    }

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("refusal")
    public void setRefusal(String refusal) {
        this.refusal = refusal;
    }

    @JsonGetter("refusal")
    public String getRefusal() {
        return this.refusal;
    }

    @JsonSetter("tool_calls")
    public void setToolCalls(java.util.List<String> toolCalls) {
        this.toolCalls = toolCalls;
    }

    @JsonGetter("tool_calls")
    public java.util.List<String> getToolCalls() {
        return this.toolCalls;
    }
}

