/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class Error {
    private ErrorDetail error;

    @JsonSetter("error")
    public void setError(ErrorDetail error) {
        this.error = error;
    }

    @JsonGetter("error")
    public ErrorDetail getError() {
        return this.error;
    }
}

