/**
 * PromptTokensDetails automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class PromptTokensDetails {
    private Integer audioTokens;
    private Integer cachedTokens;

    @JsonSetter("audio_tokens")
    public void setAudioTokens(Integer audioTokens) {
        this.audioTokens = audioTokens;
    }

    @JsonGetter("audio_tokens")
    public Integer getAudioTokens() {
        return this.audioTokens;
    }

    @JsonSetter("cached_tokens")
    public void setCachedTokens(Integer cachedTokens) {
        this.cachedTokens = cachedTokens;
    }

    @JsonGetter("cached_tokens")
    public Integer getCachedTokens() {
        return this.cachedTokens;
    }
}

