/**
 * ResponseRequestToolFunction automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("Defines a function in your own code the model can choose to call.")
public class ResponseRequestToolFunction extends ResponseRequestTool {
    @JsonPropertyDescription("The name of the function to call.")
    private String name;
    @JsonPropertyDescription("A JSON schema object describing the parameters of the function.")
    private Object parameters;
    @JsonPropertyDescription("Whether to enforce strict parameter validation. Default true.")
    private Boolean strict;
    @JsonPropertyDescription("The type of the function tool. Always function.")
    private String type = "function";
    @JsonPropertyDescription("A description of the function. Used by the model to determine whether or not to call the function.")
    private String description;

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("parameters")
    public void setParameters(Object parameters) {
        this.parameters = parameters;
    }

    @JsonGetter("parameters")
    public Object getParameters() {
        return this.parameters;
    }

    @JsonSetter("strict")
    public void setStrict(Boolean strict) {
        this.strict = strict;
    }

    @JsonGetter("strict")
    public Boolean getStrict() {
        return this.strict;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    @JsonGetter("description")
    public String getDescription() {
        return this.description;
    }
}

