/**
 * ResponseRequest automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseRequest {
    @JsonPropertyDescription("Whether to run the model response in the background.")
    private Boolean background;
    @JsonPropertyDescription("The conversation that this response belongs to. Items from this conversation are prepended to input_items for this response request. Input items and output items from this response are automatically added to this conversation after this response completes.")
    private ResponseRequestConversation conversation;
    @JsonPropertyDescription("Specify additional output data to include in the model response.")
    private java.util.List<String> include;
    @JsonPropertyDescription("Text, image, or file inputs to the model, used to generate a response.")
    private String input;
    @JsonPropertyDescription("A system (or developer) message inserted into the model's context.  When using along with previous_response_id, the instructions from a previous response will not be carried over to the next response. This makes it simple to swap out system (or developer) messages in new responses.")
    private String instructions;
    @JsonPropertyDescription("An upper bound for the number of tokens that can be generated for a response, including visible output tokens and reasoning tokens.")
    private String maxOutputTokens;
    @JsonPropertyDescription("The maximum number of total calls to built-in tools that can be processed in a response. This maximum number applies across all built-in tool calls, not per individual tool. Any further attempts to call a tool by the model will be ignored.")
    private String maxToolCalls;
    @JsonPropertyDescription("Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format, and querying for objects via API or the dashboard.  Keys are strings with a maximum length of 64 characters. Values are strings with a maximum length of 512 characters.")
    private java.util.Map<String, String> metadata;
    @JsonPropertyDescription("Model ID used to generate the response, like gpt-4o or o3. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the model guide to browse and compare available models.")
    private String model;
    @JsonPropertyDescription("Whether to allow the model to run tool calls in parallel.")
    private Boolean parallelToolCalls;
    @JsonPropertyDescription("The unique ID of the previous response to the model. Use this to create multi-turn conversations. Learn more about conversation state. Cannot be used in conjunction with conversation.")
    private String previousResponseId;
    @JsonPropertyDescription("Reference to a prompt template and its variables.")
    private ResponsePrompt prompt;
    @JsonPropertyDescription("Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the user field.")
    private String promptCacheKey;
    @JsonPropertyDescription("gpt-5 and o-series models only")
    private ResponseReasoning reasoning;
    @JsonPropertyDescription("A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies. The IDs should be a string that uniquely identifies each user. We recommend hashing their username or email address, in order to avoid sending us any identifying information.")
    private String safetyIdentifier;
    @JsonPropertyDescription("Specifies the processing type used for serving the request.")
    private String serviceTier;
    @JsonPropertyDescription("Whether to store the generated model response for later retrieval via API.")
    private Boolean store;
    @JsonPropertyDescription("What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or top_p but not both.")
    private Double temperature;
    @JsonPropertyDescription("Configuration options for a text response from the model. Can be plain text or structured JSON data.")
    private ResponseText text;
    @JsonPropertyDescription("How the model should select which tool (or tools) to use when generating a response. See the tools parameter to see how to specify which tools the model can call.")
    private String toolChoice;
    @JsonPropertyDescription("An array of tools the model may call while generating a response. You can specify which tool to use by setting the tool_choice parameter.")
    private java.util.List<ResponseTool> tools;
    @JsonPropertyDescription("An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability.")
    private Integer topLogprobs;
    @JsonPropertyDescription("An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both.")
    private Double topP;
    @JsonPropertyDescription("The truncation strategy to use for the model response.")
    private String truncation;

    @JsonSetter("background")
    public void setBackground(Boolean background) {
        this.background = background;
    }

    @JsonGetter("background")
    public Boolean getBackground() {
        return this.background;
    }

    @JsonSetter("conversation")
    public void setConversation(ResponseRequestConversation conversation) {
        this.conversation = conversation;
    }

    @JsonGetter("conversation")
    public ResponseRequestConversation getConversation() {
        return this.conversation;
    }

    @JsonSetter("include")
    public void setInclude(java.util.List<String> include) {
        this.include = include;
    }

    @JsonGetter("include")
    public java.util.List<String> getInclude() {
        return this.include;
    }

    @JsonSetter("input")
    public void setInput(String input) {
        this.input = input;
    }

    @JsonGetter("input")
    public String getInput() {
        return this.input;
    }

    @JsonSetter("instructions")
    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    @JsonGetter("instructions")
    public String getInstructions() {
        return this.instructions;
    }

    @JsonSetter("max_output_tokens")
    public void setMaxOutputTokens(String maxOutputTokens) {
        this.maxOutputTokens = maxOutputTokens;
    }

    @JsonGetter("max_output_tokens")
    public String getMaxOutputTokens() {
        return this.maxOutputTokens;
    }

    @JsonSetter("max_tool_calls")
    public void setMaxToolCalls(String maxToolCalls) {
        this.maxToolCalls = maxToolCalls;
    }

    @JsonGetter("max_tool_calls")
    public String getMaxToolCalls() {
        return this.maxToolCalls;
    }

    @JsonSetter("metadata")
    public void setMetadata(java.util.Map<String, String> metadata) {
        this.metadata = metadata;
    }

    @JsonGetter("metadata")
    public java.util.Map<String, String> getMetadata() {
        return this.metadata;
    }

    @JsonSetter("model")
    public void setModel(String model) {
        this.model = model;
    }

    @JsonGetter("model")
    public String getModel() {
        return this.model;
    }

    @JsonSetter("parallel_tool_calls")
    public void setParallelToolCalls(Boolean parallelToolCalls) {
        this.parallelToolCalls = parallelToolCalls;
    }

    @JsonGetter("parallel_tool_calls")
    public Boolean getParallelToolCalls() {
        return this.parallelToolCalls;
    }

    @JsonSetter("previous_response_id")
    public void setPreviousResponseId(String previousResponseId) {
        this.previousResponseId = previousResponseId;
    }

    @JsonGetter("previous_response_id")
    public String getPreviousResponseId() {
        return this.previousResponseId;
    }

    @JsonSetter("prompt")
    public void setPrompt(ResponsePrompt prompt) {
        this.prompt = prompt;
    }

    @JsonGetter("prompt")
    public ResponsePrompt getPrompt() {
        return this.prompt;
    }

    @JsonSetter("prompt_cache_key")
    public void setPromptCacheKey(String promptCacheKey) {
        this.promptCacheKey = promptCacheKey;
    }

    @JsonGetter("prompt_cache_key")
    public String getPromptCacheKey() {
        return this.promptCacheKey;
    }

    @JsonSetter("reasoning")
    public void setReasoning(ResponseReasoning reasoning) {
        this.reasoning = reasoning;
    }

    @JsonGetter("reasoning")
    public ResponseReasoning getReasoning() {
        return this.reasoning;
    }

    @JsonSetter("safety_identifier")
    public void setSafetyIdentifier(String safetyIdentifier) {
        this.safetyIdentifier = safetyIdentifier;
    }

    @JsonGetter("safety_identifier")
    public String getSafetyIdentifier() {
        return this.safetyIdentifier;
    }

    @JsonSetter("service_tier")
    public void setServiceTier(String serviceTier) {
        this.serviceTier = serviceTier;
    }

    @JsonGetter("service_tier")
    public String getServiceTier() {
        return this.serviceTier;
    }

    @JsonSetter("store")
    public void setStore(Boolean store) {
        this.store = store;
    }

    @JsonGetter("store")
    public Boolean getStore() {
        return this.store;
    }

    @JsonSetter("temperature")
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    @JsonGetter("temperature")
    public Double getTemperature() {
        return this.temperature;
    }

    @JsonSetter("text")
    public void setText(ResponseText text) {
        this.text = text;
    }

    @JsonGetter("text")
    public ResponseText getText() {
        return this.text;
    }

    @JsonSetter("tool_choice")
    public void setToolChoice(String toolChoice) {
        this.toolChoice = toolChoice;
    }

    @JsonGetter("tool_choice")
    public String getToolChoice() {
        return this.toolChoice;
    }

    @JsonSetter("tools")
    public void setTools(java.util.List<ResponseTool> tools) {
        this.tools = tools;
    }

    @JsonGetter("tools")
    public java.util.List<ResponseTool> getTools() {
        return this.tools;
    }

    @JsonSetter("top_logprobs")
    public void setTopLogprobs(Integer topLogprobs) {
        this.topLogprobs = topLogprobs;
    }

    @JsonGetter("top_logprobs")
    public Integer getTopLogprobs() {
        return this.topLogprobs;
    }

    @JsonSetter("top_p")
    public void setTopP(Double topP) {
        this.topP = topP;
    }

    @JsonGetter("top_p")
    public Double getTopP() {
        return this.topP;
    }

    @JsonSetter("truncation")
    public void setTruncation(String truncation) {
        this.truncation = truncation;
    }

    @JsonGetter("truncation")
    public String getTruncation() {
        return this.truncation;
    }
}

