/**
 * ResponseRequestInputFunctionCall automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A tool call to run a function. See the function calling guide for more information.")
public class ResponseRequestInputFunctionCall extends ResponseRequestInput {
    @JsonPropertyDescription("A JSON string of the arguments to pass to the function.")
    private String arguments;
    @JsonPropertyDescription("The unique ID of the function tool call generated by the model.")
    private String callId;
    @JsonPropertyDescription("The name of the function to run.")
    private String name;
    @JsonPropertyDescription("The type of the function tool call. Always function_call.")
    private String type = "function_call";
    @JsonPropertyDescription("The unique ID of the function tool call.")
    private String id;
    @JsonPropertyDescription("The status of the item. One of in_progress, completed, or incomplete. Populated when items are returned via API.")
    private String status;

    @JsonSetter("arguments")
    public void setArguments(String arguments) {
        this.arguments = arguments;
    }

    @JsonGetter("arguments")
    public String getArguments() {
        return this.arguments;
    }

    @JsonSetter("call_id")
    public void setCallId(String callId) {
        this.callId = callId;
    }

    @JsonGetter("call_id")
    public String getCallId() {
        return this.callId;
    }

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }
}

