/**
 * ResponseRequestInputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseRequestInputMessage extends ResponseRequestInput {
    @JsonPropertyDescription("Text, image, or audio input to the model, used to generate a response. Can also contain previous assistant responses.")
    private java.util.List<String> content;
    @JsonPropertyDescription("The role of the message input. One of user, assistant, system, or developer.")
    private String role;
    @JsonPropertyDescription("The type of the message input. Always message.")
    private String type = "message";

    @JsonSetter("content")
    public void setContent(java.util.List<String> content) {
        this.content = content;
    }

    @JsonGetter("content")
    public java.util.List<String> getContent() {
        return this.content;
    }

    @JsonSetter("role")
    public void setRole(String role) {
        this.role = role;
    }

    @JsonGetter("role")
    public String getRole() {
        return this.role;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

