/**
 * ResponseToolWebSearchFilter automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseToolWebSearchFilter {
    @JsonPropertyDescription("Allowed domains for the search. If not provided, all domains are allowed. Subdomains of the provided domains are allowed as well.")
    private java.util.List<String> allowedDomains;

    @JsonSetter("allowed_domains")
    public void setAllowedDomains(java.util.List<String> allowedDomains) {
        this.allowedDomains = allowedDomains;
    }

    @JsonGetter("allowed_domains")
    public java.util.List<String> getAllowedDomains() {
        return this.allowedDomains;
    }
}

