/**
 * ResponseRequestTextFormatJsonSchema automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseRequestTextFormatJsonSchema extends ResponseRequestTextFormat {
    @JsonPropertyDescription("The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.")
    private String name;
    @JsonPropertyDescription("The schema for the response format, described as a JSON Schema object.")
    private Object schema;
    @JsonPropertyDescription("The type of response format being defined. Always json_schema.")
    private String type = "json_schema";
    @JsonPropertyDescription("A description of what the response format is for, used by the model to determine how to respond in the format.")
    private String description;
    @JsonPropertyDescription("Whether to enable strict schema adherence when generating the output.")
    private Boolean strict;

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("schema")
    public void setSchema(Object schema) {
        this.schema = schema;
    }

    @JsonGetter("schema")
    public Object getSchema() {
        return this.schema;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    @JsonGetter("description")
    public String getDescription() {
        return this.description;
    }

    @JsonSetter("strict")
    public void setStrict(Boolean strict) {
        this.strict = strict;
    }

    @JsonGetter("strict")
    public Boolean getStrict() {
        return this.strict;
    }
}

