/**
 * ResponseReasoning automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseReasoning {
    @JsonPropertyDescription("Constrains effort on reasoning for reasoning models. Currently supported values are minimal, low, medium, and high. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response.  Note: The gpt-5-pro model defaults to (and only supports) high reasoning effort.")
    private String effort;
    @JsonPropertyDescription("A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. One of auto, concise, or detailed.")
    private String summary;

    @JsonSetter("effort")
    public void setEffort(String effort) {
        this.effort = effort;
    }

    @JsonGetter("effort")
    public String getEffort() {
        return this.effort;
    }

    @JsonSetter("summary")
    public void setSummary(String summary) {
        this.summary = summary;
    }

    @JsonGetter("summary")
    public String getSummary() {
        return this.summary;
    }
}

