/**
 * ResponseToolWebSearch automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseToolWebSearch extends ResponseTool {
    @JsonPropertyDescription("The type of the web search tool. One of web_search or web_search_2025_08_26.")
    private String type;
    @JsonPropertyDescription("Filters for the search.")
    private ResponseToolWebSearchFilter filters;
    @JsonPropertyDescription("High level guidance for the amount of context window space to use for the search. One of low, medium, or high. medium is the default.")
    private String searchContextSize;
    @JsonPropertyDescription("The approximate location of the user.")
    private ResponseToolWebSearchLocation userLocation;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("filters")
    public void setFilters(ResponseToolWebSearchFilter filters) {
        this.filters = filters;
    }

    @JsonGetter("filters")
    public ResponseToolWebSearchFilter getFilters() {
        return this.filters;
    }

    @JsonSetter("search_context_size")
    public void setSearchContextSize(String searchContextSize) {
        this.searchContextSize = searchContextSize;
    }

    @JsonGetter("search_context_size")
    public String getSearchContextSize() {
        return this.searchContextSize;
    }

    @JsonSetter("user_location")
    public void setUserLocation(ResponseToolWebSearchLocation userLocation) {
        this.userLocation = userLocation;
    }

    @JsonGetter("user_location")
    public ResponseToolWebSearchLocation getUserLocation() {
        return this.userLocation;
    }
}

