/**
 * ResponseText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseText {
    @JsonPropertyDescription("An object specifying the format that the model must output.")
    private ResponseTextFormat format;
    @JsonPropertyDescription("Constrains the verbosity of the model's response. Lower values will result in more concise responses, while higher values will result in more verbose responses. Currently supported values are low, medium, and high.")
    private String verbosity;

    @JsonSetter("format")
    public void setFormat(ResponseTextFormat format) {
        this.format = format;
    }

    @JsonGetter("format")
    public ResponseTextFormat getFormat() {
        return this.format;
    }

    @JsonSetter("verbosity")
    public void setVerbosity(String verbosity) {
        this.verbosity = verbosity;
    }

    @JsonGetter("verbosity")
    public String getVerbosity() {
        return this.verbosity;
    }
}

