/**
 * ResponsePrompt automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponsePrompt {
    @JsonPropertyDescription("The unique identifier of the prompt template to use.")
    private String id;
    @JsonPropertyDescription("Optional map of values to substitute in for variables in your prompt. The substitution values can either be strings, or other Response input types like images or files.")
    private java.util.Map<String, String> variables;
    @JsonPropertyDescription("Optional version of the prompt template.")
    private String version;

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("variables")
    public void setVariables(java.util.Map<String, String> variables) {
        this.variables = variables;
    }

    @JsonGetter("variables")
    public java.util.Map<String, String> getVariables() {
        return this.variables;
    }

    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    @JsonGetter("version")
    public String getVersion() {
        return this.version;
    }
}

