/**
 * ResponseRequestInputMcpListTools automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("A list of tools available on an MCP server.")
public class ResponseRequestInputMcpListTools extends ResponseRequestInput {
    @JsonPropertyDescription("The unique ID of the list.")
    private String id;
    @JsonPropertyDescription("The label of the MCP server.")
    private String serverLabel;
    @JsonPropertyDescription("The tools available on the server.")
    private java.util.List<ResponseMCPTool> tools;
    @JsonPropertyDescription("Error message if the server could not list tools.")
    private String error;
    @JsonPropertyDescription("The type of the item. Always mcp_list_tools.")
    private String type = "mcp_list_tools";

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("server_label")
    public void setServerLabel(String serverLabel) {
        this.serverLabel = serverLabel;
    }

    @JsonGetter("server_label")
    public String getServerLabel() {
        return this.serverLabel;
    }

    @JsonSetter("tools")
    public void setTools(java.util.List<ResponseMCPTool> tools) {
        this.tools = tools;
    }

    @JsonGetter("tools")
    public java.util.List<ResponseMCPTool> getTools() {
        return this.tools;
    }

    @JsonSetter("error")
    public void setError(String error) {
        this.error = error;
    }

    @JsonGetter("error")
    public String getError() {
        return this.error;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

