/**
 * ResponseMCPTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseMCPTool {
    @JsonPropertyDescription("The JSON schema describing the tool's input.")
    private Object inputSchema;
    @JsonPropertyDescription("The name of the tool.")
    private String name;
    @JsonPropertyDescription("Additional annotations about the tool.")
    private java.util.Map<String, String> annotations;
    @JsonPropertyDescription("The description of the tool.")
    private String description;

    @JsonSetter("input_schema")
    public void setInputSchema(Object inputSchema) {
        this.inputSchema = inputSchema;
    }

    @JsonGetter("input_schema")
    public Object getInputSchema() {
        return this.inputSchema;
    }

    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonGetter("name")
    public String getName() {
        return this.name;
    }

    @JsonSetter("annotations")
    public void setAnnotations(java.util.Map<String, String> annotations) {
        this.annotations = annotations;
    }

    @JsonGetter("annotations")
    public java.util.Map<String, String> getAnnotations() {
        return this.annotations;
    }

    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    @JsonGetter("description")
    public String getDescription() {
        return this.description;
    }
}

