/**
 * ResponseToolWebSearchLocation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseToolWebSearchLocation {
    @JsonPropertyDescription("Free text input for the city of the user, e.g. San Francisco.")
    private String city;
    @JsonPropertyDescription("The two-letter ISO country code of the user, e.g. US.")
    private String country;
    @JsonPropertyDescription("Free text input for the region of the user, e.g. California.")
    private String region;
    @JsonPropertyDescription("The IANA timezone of the user, e.g. America/Los_Angeles.")
    private String timezone;
    @JsonPropertyDescription("The type of location approximation. Always approximate.")
    private String type;

    @JsonSetter("city")
    public void setCity(String city) {
        this.city = city;
    }

    @JsonGetter("city")
    public String getCity() {
        return this.city;
    }

    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }

    @JsonGetter("country")
    public String getCountry() {
        return this.country;
    }

    @JsonSetter("region")
    public void setRegion(String region) {
        this.region = region;
    }

    @JsonGetter("region")
    public String getRegion() {
        return this.region;
    }

    @JsonSetter("timezone")
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    @JsonGetter("timezone")
    public String getTimezone() {
        return this.timezone;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

