/**
 * ResponseResponseOutputMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("An output message from the model.")
public class ResponseResponseOutputMessage extends ResponseResponseOutput {
    @JsonPropertyDescription("The content of the output message.")
    private java.util.List<String> content;
    @JsonPropertyDescription("The unique ID of the output message.")
    private String id;
    @JsonPropertyDescription("The role of the output message. Always assistant.")
    private String role;
    @JsonPropertyDescription("The status of the message input. One of in_progress, completed, or incomplete. Populated when input items are returned via API.")
    private String status;
    @JsonPropertyDescription("The type of the output message. Always message.")
    private String type;

    @JsonSetter("content")
    public void setContent(java.util.List<String> content) {
        this.content = content;
    }

    @JsonGetter("content")
    public java.util.List<String> getContent() {
        return this.content;
    }

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("role")
    public void setRole(String role) {
        this.role = role;
    }

    @JsonGetter("role")
    public String getRole() {
        return this.role;
    }

    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

