/**
 * ResponseTool automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = ResponseToolFunction.class, name = "function"),
    @JsonSubTypes.Type(value = ResponseToolMCP.class, name = "mcp"),
    @JsonSubTypes.Type(value = ResponseToolWebSearch.class, name = "web_search"),
})
public abstract class ResponseTool {
    private String type;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

