/**
 * ResponseRequestInput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = ResponseRequestInputFunctionCall.class, name = "function_call"),
    @JsonSubTypes.Type(value = ResponseRequestInputFunctionCallOutput.class, name = "function_call_output"),
    @JsonSubTypes.Type(value = ResponseRequestInputMessage.class, name = "message"),
})
@JsonClassDescription("An item representing part of the context for the response to be generated by the model. Can contain text, images, and audio inputs, as well as previous assistant responses and tool call outputs.")
public abstract class ResponseRequestInput {
    private String type;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

