/**
 * ResponseRequestTextFormatText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseRequestTextFormatText extends ResponseRequestTextFormat {
    @JsonPropertyDescription("The type of response format being defined. Always text.")
    private String type = "text";

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

