/**
 * ResponseResponseError automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseResponseError {
    @JsonPropertyDescription("The error code for the response.")
    private String code;
    @JsonPropertyDescription("A human-readable description of the error.")
    private String message;

    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    @JsonGetter("code")
    public String getCode() {
        return this.code;
    }

    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    @JsonGetter("message")
    public String getMessage() {
        return this.message;
    }
}

