/**
 * ResponseResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseResponse {
    @JsonPropertyDescription("Unix timestamp (in seconds) of when this Response was created.")
    private Integer createdAt;
    @JsonPropertyDescription("An error object returned when the model fails to generate a Response.")
    private ResponseResponseError error;
    @JsonPropertyDescription("Unique identifier for this Response.")
    private String id;
    @JsonPropertyDescription("Details about why the response is incomplete.")
    private String incompleteDetails;
    @JsonPropertyDescription("The object type of this resource - always set to response.")
    private String object;
    @JsonPropertyDescription("An array of content items generated by the model.")
    private java.util.List<ResponseResponseOutput> output;

    @JsonSetter("created_at")
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    @JsonGetter("created_at")
    public Integer getCreatedAt() {
        return this.createdAt;
    }

    @JsonSetter("error")
    public void setError(ResponseResponseError error) {
        this.error = error;
    }

    @JsonGetter("error")
    public ResponseResponseError getError() {
        return this.error;
    }

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("incomplete_details")
    public void setIncompleteDetails(String incompleteDetails) {
        this.incompleteDetails = incompleteDetails;
    }

    @JsonGetter("incomplete_details")
    public String getIncompleteDetails() {
        return this.incompleteDetails;
    }

    @JsonSetter("object")
    public void setObject(String object) {
        this.object = object;
    }

    @JsonGetter("object")
    public String getObject() {
        return this.object;
    }

    @JsonSetter("output")
    public void setOutput(java.util.List<ResponseResponseOutput> output) {
        this.output = output;
    }

    @JsonGetter("output")
    public java.util.List<ResponseResponseOutput> getOutput() {
        return this.output;
    }
}

