/**
 * ResponseRequestInputFunctionCallOutput automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

@JsonClassDescription("The output of a function tool call.")
public class ResponseRequestInputFunctionCallOutput extends ResponseRequestInput {
    @JsonPropertyDescription("The unique ID of the function tool call generated by the model.")
    private String callId;
    @JsonPropertyDescription("Text, image, or file output of the function tool call.")
    private String output;
    @JsonPropertyDescription("The type of the function tool call output. Always function_call_output.")
    private String type = "function_call_output";
    @JsonPropertyDescription("The unique ID of the function tool call output. Populated when this item is returned via API.")
    private String id;
    @JsonPropertyDescription("The status of the item. One of in_progress, completed, or incomplete. Populated when items are returned via API.")
    private String status;

    @JsonSetter("call_id")
    public void setCallId(String callId) {
        this.callId = callId;
    }

    @JsonGetter("call_id")
    public String getCallId() {
        return this.callId;
    }

    @JsonSetter("output")
    public void setOutput(String output) {
        this.output = output;
    }

    @JsonGetter("output")
    public String getOutput() {
        return this.output;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonGetter("id")
    public String getId() {
        return this.id;
    }

    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    @JsonGetter("status")
    public String getStatus() {
        return this.status;
    }
}

