/**
 * ResponseToolMCP automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.openai;

import com.fasterxml.jackson.annotation.*;

public class ResponseToolMCP extends ResponseTool {
    @JsonPropertyDescription("A label for this MCP server, used to identify it in tool calls.")
    private String serverLabel;
    @JsonPropertyDescription("The type of the MCP tool. Always mcp.")
    private String type;
    @JsonPropertyDescription("List of allowed tool names or a filter object.")
    private java.util.List<String> allowedTools;
    @JsonPropertyDescription("An OAuth access token that can be used with a remote MCP server, either with a custom MCP server URL or a service connector. Your application must handle the OAuth authorization flow and provide the token here.")
    private String authorization;
    @JsonPropertyDescription("Identifier for service connectors, like those available in ChatGPT. One of server_url or connector_id must be provided.")
    private String connectorId;
    @JsonPropertyDescription("Optional HTTP headers to send to the MCP server. Use for authentication or other purposes.")
    private java.util.Map<String, String> headers;
    @JsonPropertyDescription("Specify which of the MCP server's tools require approval.")
    private String requireApproval;
    @JsonPropertyDescription("Optional description of the MCP server, used to provide more context.")
    private String serverDescription;
    @JsonPropertyDescription("The URL for the MCP server. One of server_url or connector_id must be provided.")
    private String serverUrl;

    @JsonSetter("server_label")
    public void setServerLabel(String serverLabel) {
        this.serverLabel = serverLabel;
    }

    @JsonGetter("server_label")
    public String getServerLabel() {
        return this.serverLabel;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("allowed_tools")
    public void setAllowedTools(java.util.List<String> allowedTools) {
        this.allowedTools = allowedTools;
    }

    @JsonGetter("allowed_tools")
    public java.util.List<String> getAllowedTools() {
        return this.allowedTools;
    }

    @JsonSetter("authorization")
    public void setAuthorization(String authorization) {
        this.authorization = authorization;
    }

    @JsonGetter("authorization")
    public String getAuthorization() {
        return this.authorization;
    }

    @JsonSetter("connector_id")
    public void setConnectorId(String connectorId) {
        this.connectorId = connectorId;
    }

    @JsonGetter("connector_id")
    public String getConnectorId() {
        return this.connectorId;
    }

    @JsonSetter("headers")
    public void setHeaders(java.util.Map<String, String> headers) {
        this.headers = headers;
    }

    @JsonGetter("headers")
    public java.util.Map<String, String> getHeaders() {
        return this.headers;
    }

    @JsonSetter("require_approval")
    public void setRequireApproval(String requireApproval) {
        this.requireApproval = requireApproval;
    }

    @JsonGetter("require_approval")
    public String getRequireApproval() {
        return this.requireApproval;
    }

    @JsonSetter("server_description")
    public void setServerDescription(String serverDescription) {
        this.serverDescription = serverDescription;
    }

    @JsonGetter("server_description")
    public String getServerDescription() {
        return this.serverDescription;
    }

    @JsonSetter("server_url")
    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }

    @JsonGetter("server_url")
    public String getServerUrl() {
        return this.serverUrl;
    }
}

